name: Karl

on: 
  workflow_dispatch:
    # For manual workflow run
  schedule: 
    # 55 minutes on every hour
    - cron: '0 22 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        cd docs/_data
        wget -O repos.json https://api.github.com/users/twert627/repos
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Karl has updated repo list"
        git push 
